name: ci
on: [push, pull_request]
jobs:
  build-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 13
      - name: build
        run: ./gradlew -b ci.gradle package